version: '2'
services:
  db:
    image: mysql
    env_file:
      - MySQL.env
    volumes:
      - ./datadir:/var/lib/mysql
  camera:
    build: .
    env_file:
      - MySQL.env
      - Shinobi.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./config:/config
      - ./videos:/opt/shinobi/videos
    depends_on:
      - db
    ports:
      - "8080:8080"
    command: node /opt/shinobi/camera.js
  cron:
    build: .
    env_file:
      - MySQL.env
      - Shinobi.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./config:/config
      - ./videos:/opt/shinobi/videos
    depends_on:
      - db
    command: node /opt/shinobi/cron.js
  motion:
    build: .
    env_file:
      - MySQL.env
      - Shinobi.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./config:/config
      - ./videos:/opt/shinobi/videos
    depends_on:
      - db
    command: node /opt/shinobi/plugins/motion/shinobi-motion.js
