version: '2'
services:
  app:
    build: .
    env_file:
      - SQLite3.env
      - Shinobi.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./config:/config
      - ./videos:/opt/shinobi/videos
      - ./dbdata:/opt/dbdata
    ports:
      - "8080:8080"
    command: pm2-docker pm2Shinobi.yml
    