# This workflow builds the Docker images and pushes the images to Docker Hub

name: Docker-CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ v2 ]
  pull_request:
    branches: [ v2 ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check-out code
        uses: actions/checkout@v2

      - name: Build and push Docker image (microservice)
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: migoller/shinobiv2
          tags: microservice-alpine
          tag_with_sha: true
          push: false
          add_git_labels: true
          build_args: ARG_AIO=false
